// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicTacToe.Datasource.Model;

#nullable disable

namespace TicTacToe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627113306_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicTacToe.Datasource.Model.GameDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("GameOutcome")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "gameOutcome");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TicTacToe.Datasource.Model.GameDTO", b =>
                {
                    b.OwnsOne("GameBoardDTO", "GameBoard", b1 =>
                        {
                            b1.Property<Guid>("GameDTOId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BoardMatrixJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GameDTOId");

                            b1.ToTable("Games");

                            b1.HasAnnotation("Relational:JsonPropertyName", "gameBoard");

                            b1.WithOwner()
                                .HasForeignKey("GameDTOId");
                        });

                    b.Navigation("GameBoard")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
